package modelo;
// Generated 26/02/2018 07:08:39 AM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Explaboral generated by hbm2java
 */
public class Explaboral  implements java.io.Serializable {


     private int idexplaboral;
     private Profesionista profesionista;
     private String empresa;
     private String cargo;
     private Date periodoc;
     private Date periodot;

    public Explaboral() {
    }

	
    public Explaboral(int idexplaboral) {
        this.idexplaboral = idexplaboral;
    }
    public Explaboral(int idexplaboral, Profesionista profesionista, String empresa, String cargo, Date periodoc, Date periodot) {
       this.idexplaboral = idexplaboral;
       this.profesionista = profesionista;
       this.empresa = empresa;
       this.cargo = cargo;
       this.periodoc = periodoc;
       this.periodot = periodot;
    }
   
    public int getIdexplaboral() {
        return this.idexplaboral;
    }
    
    public void setIdexplaboral(int idexplaboral) {
        this.idexplaboral = idexplaboral;
    }
    public Profesionista getProfesionista() {
        return this.profesionista;
    }
    
    public void setProfesionista(Profesionista profesionista) {
        this.profesionista = profesionista;
    }
    public String getEmpresa() {
        return this.empresa;
    }
    
    public void setEmpresa(String empresa) {
        this.empresa = empresa;
    }
    public String getCargo() {
        return this.cargo;
    }
    
    public void setCargo(String cargo) {
        this.cargo = cargo;
    }
    public Date getPeriodoc() {
        return this.periodoc;
    }
    
    public void setPeriodoc(Date periodoc) {
        this.periodoc = periodoc;
    }
    public Date getPeriodot() {
        return this.periodot;
    }
    
    public void setPeriodot(Date periodot) {
        this.periodot = periodot;
    }




}


