package modelo;
// Generated 26/02/2018 07:08:39 AM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Formacionac generated by hbm2java
 */
public class Formacionac  implements java.io.Serializable {


     private int idformacionac;
     private Profesionista profesionista;
     private String colegio;
     private Integer nivel;
     private Date periodoc;
     private Date periodot;

    public Formacionac() {
    }

	
    public Formacionac(int idformacionac) {
        this.idformacionac = idformacionac;
    }
    public Formacionac(int idformacionac, Profesionista profesionista, String colegio, Integer nivel, Date periodoc, Date periodot) {
       this.idformacionac = idformacionac;
       this.profesionista = profesionista;
       this.colegio = colegio;
       this.nivel = nivel;
       this.periodoc = periodoc;
       this.periodot = periodot;
    }
   
    public int getIdformacionac() {
        return this.idformacionac;
    }
    
    public void setIdformacionac(int idformacionac) {
        this.idformacionac = idformacionac;
    }
    public Profesionista getProfesionista() {
        return this.profesionista;
    }
    
    public void setProfesionista(Profesionista profesionista) {
        this.profesionista = profesionista;
    }
    public String getColegio() {
        return this.colegio;
    }
    
    public void setColegio(String colegio) {
        this.colegio = colegio;
    }
    public Integer getNivel() {
        return this.nivel;
    }
    
    public void setNivel(Integer nivel) {
        this.nivel = nivel;
    }
    public Date getPeriodoc() {
        return this.periodoc;
    }
    
    public void setPeriodoc(Date periodoc) {
        this.periodoc = periodoc;
    }
    public Date getPeriodot() {
        return this.periodot;
    }
    
    public void setPeriodot(Date periodot) {
        this.periodot = periodot;
    }




}


