package modelo;
// Generated 26/02/2018 07:08:39 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Profesionista generated by hbm2java
 */
public class Profesionista  implements java.io.Serializable {


     private int idprofesionista;
     private String nombre;
     private String apellidop;
     private String nacionalidad;
     private String carrera;
     private String telefono;
     private String contrasenia;
     private String foto;
     private Set postulars = new HashSet(0);
     private Set habilidads = new HashSet(0);
     private Set formacionacs = new HashSet(0);
     private Set explaborals = new HashSet(0);

    public Profesionista() {
    }

	
    public Profesionista(int idprofesionista, String nombre, String apellidop, String nacionalidad, String carrera, String telefono, String contrasenia) {
        this.idprofesionista = idprofesionista;
        this.nombre = nombre;
        this.apellidop = apellidop;
        this.nacionalidad = nacionalidad;
        this.carrera = carrera;
        this.telefono = telefono;
        this.contrasenia = contrasenia;
    }
    public Profesionista(int idprofesionista, String nombre, String apellidop, String nacionalidad, String carrera, String telefono, String contrasenia, String foto, Set postulars, Set habilidads, Set formacionacs, Set explaborals) {
       this.idprofesionista = idprofesionista;
       this.nombre = nombre;
       this.apellidop = apellidop;
       this.nacionalidad = nacionalidad;
       this.carrera = carrera;
       this.telefono = telefono;
       this.contrasenia = contrasenia;
       this.foto = foto;
       this.postulars = postulars;
       this.habilidads = habilidads;
       this.formacionacs = formacionacs;
       this.explaborals = explaborals;
    }
   
    public int getIdprofesionista() {
        return this.idprofesionista;
    }
    
    public void setIdprofesionista(int idprofesionista) {
        this.idprofesionista = idprofesionista;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getApellidop() {
        return this.apellidop;
    }
    
    public void setApellidop(String apellidop) {
        this.apellidop = apellidop;
    }
    public String getNacionalidad() {
        return this.nacionalidad;
    }
    
    public void setNacionalidad(String nacionalidad) {
        this.nacionalidad = nacionalidad;
    }
    public String getCarrera() {
        return this.carrera;
    }
    
    public void setCarrera(String carrera) {
        this.carrera = carrera;
    }
    public String getTelefono() {
        return this.telefono;
    }
    
    public void setTelefono(String telefono) {
        this.telefono = telefono;
    }
    public String getContrasenia() {
        return this.contrasenia;
    }
    
    public void setContrasenia(String contrasenia) {
        this.contrasenia = contrasenia;
    }
    public String getFoto() {
        return this.foto;
    }
    
    public void setFoto(String foto) {
        this.foto = foto;
    }
    public Set getPostulars() {
        return this.postulars;
    }
    
    public void setPostulars(Set postulars) {
        this.postulars = postulars;
    }
    public Set getHabilidads() {
        return this.habilidads;
    }
    
    public void setHabilidads(Set habilidads) {
        this.habilidads = habilidads;
    }
    public Set getFormacionacs() {
        return this.formacionacs;
    }
    
    public void setFormacionacs(Set formacionacs) {
        this.formacionacs = formacionacs;
    }
    public Set getExplaborals() {
        return this.explaborals;
    }
    
    public void setExplaborals(Set explaborals) {
        this.explaborals = explaborals;
    }




}


